### ISSUE TITLE
Add GUI parameters / fix crashes mentionned in camera.js

### ISSUE THREAD

**Issue by arthur-parmentier** [lysdexic-audio/n4m-handpose#5]
Hello!

It would be really nice to get more of the GUI to change some confidence parameters and control more of the model.

In the camera.js file, I see that things were commented because of crashes. Maybe things could be taken from the 2020 example from tensorflow?

https://github.com/tensorflow/tfjs-models/blob/master/handpose/demo/index.js

**Comment by lysdexic-audio** [comment]
Hi Arthur,

Looks like I've found the source of the crashing - I'm adding back in this feature and a whole bunch of other improvements today! I'll post here and close this issue when I push the new repo :)

**Comment by arthur-parmentier** [comment]
Hi! Thanks for the update.

Here is a little contribution from mine as well, that I use in a bigger project. I think it will help some to deal with the dict output ;)


[29052020_handpose_input.zip](https://github.com/lysdexic-audio/n4m-handpose/files/4701255/29052020_handpose_input.zip)

**Comment by arthur-parmentier** [comment]
Maybe you could include it in your repo if you think that would help others! Let me know

**Comment by lysdexic-audio** [comment]
Ah interesting - looks quite well featured! I couldn't try any of it as I'm missing the bpatchers etc.

I've actually just finished adding a neater dictionary parser along with wekinator formatting and GL rendering, i'll push the model UI controls tomorrow :)

I've linked your project in the main page too, thanks for using this in  your project :D

**Comment by arthur-parmentier** [comment]
Niceee

yep I completly forgot about the bpatchers...

I just feel that people would not take so much time taking the little parts from my project, because it is becoming quite big and complex at getting the full view on its structure and mechanisms...

I did not get what you mean by wekinator formatting, maybe you meant OSC forwarding to wekinator? What I am implementing in my project is basically an automated recording/training tool with wekinator with generic inputs (posenet, handpose, mocap stuff...)

here comes the bpatchers in the zip file, btw if you feel like making something out of it
[Main_patch.zip](https://github.com/lysdexic-audio/n4m-handpose/files/4703649/Main_patch.zip)
